version: '3.8'

services:
  rc-wa-api:
    build: .
    container_name: rc-wa-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./sessions_data:/usr/src/app/sessions_data
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=production
