version: '3.8'

services:
  rc-wa-api:
    image: ghcr.io/rodadecuia/rc-wa-api:latest
    container_name: rc-wa-api
    restart: always
    ports:
      - "${RC_WA_API_PORT:-3000}:3000"
    volumes:
      - ./sessions_data:/usr/src/app/sessions_data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
